### ISSUE TITLE
what types do ID and Long String refer to in JAVA or ParquetFile?

### ISSUE THREAD

**Issue by geralt-write-code** [ldbc/ldbc_snb_datagen_hadoop#20]
hello, 👋 . I'm using ldbc to do some benchmark on our graph. however graphs don't support csv import. I need to convert csv files to parquet files. So I want to know what do ID and Long String in graph schma exactly refer to.

<img width="656" alt="image" src="https://user-images.githubusercontent.com/59411332/180741350-2155c6f2-f1bc-49b2-bca4-9a59bb72529b.png">

**Comment by szarnyasg** [comment]
Hi @geralt-write-code, which LDBC workload are you interested in using?
We have three major workloads for database benchmarks:

- Interactive 1.0: OLTP benchmark with inserts, uses the Datagen version contained in this repository
- Interactive 2.0: OLTP benchmark with inserts and deletes, uses the Spark-based Datagen
- BI 1.0: OLAP benchmark with inserts and deletes, uses the Spark-based Datagen

The [Spark-based Datagen](https://github.com/ldbc/ldbc_snb_datagen_spark) is capable of generating parquet files, so using that would be the simplest approach.

If you would like to use the old Hadoop-based Datagen and do the conversion manually, the meaning of the types is the following: 

> `String` variable length text of size 40 Unicode characters
> `Long String` variable length text of size 256 Unicode characters
> `Text` variable length text of size 2000 Unicode characters

(https://ldbcouncil.org/ldbc_snb_docs/ldbc-snb-specification.pdf, page 15)

**Comment by geralt-write-code** [comment]
> Hi @geralt-write-code, which LDBC workload are you interested in using? We have three major workloads for database benchmarks:
> 
> * Interactive 1.0: OLTP benchmark with inserts, uses the Datagen version contained in this repository
> * Interactive 2.0: OLTP benchmark with inserts and deletes, uses the Spark-based Datagen
> * BI 1.0: OLAP benchmark with inserts and deletes, uses the Spark-based Datagen
> 
> The [Spark-based Datagen](https://github.com/ldbc/ldbc_snb_datagen_spark) is capable of generating parquet files, so using that would be the simplest approach.
> 
> If you would like to use the old Hadoop-based Datagen and do the conversion manually, the meaning of the types is the following:
> 
> > `String` variable length text of size 40 Unicode characters
> > `Long String` variable length text of size 256 Unicode characters
> > `Text` variable length text of size 2000 Unicode characters
> 
> (https://ldbcouncil.org/ldbc_snb_docs/ldbc-snb-specification.pdf, page 15)

hello @szarnyasg , I'm using Interactive 1.0 workloads and thank you for your reply! This will be very helpful for my benchmark! And maybe I'll also try Interactive 2.0 in the future

**Comment by szarnyasg** [comment]
No problem, glad it helped. If you're looking for a convenient Paquet writer, it might be worth checking out [DuckDB's Parquet features](https://duckdb.org/docs/data/parquet#writing-to-parquet-files).
