### ISSUE TITLE
hadoop generate data, how to set date format

### ISSUE THREAD

**Issue by suzhaojun** [ldbc/ldbc_snb_datagen_hadoop#21]
I use hadoop to generate data set.
But, generate data date format is 
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/22903601/216291094-7ee181ea-ba62-4fcb-90b7-676cf5166b49.png">

I want yyyy-MM-dd hh:mm:ss

How to set generate data date format

**Comment by szarnyasg** [comment]
@suzhaojun you need millisecond precision for valid benchmarks. If you only need the timestamps up to second precision:

```console
ldbc.snb.datagen.util.formatter.StringDateFormatter.dateTimeFormat:yyyy-MM-dd'T'HH:mm:ss
```
