### ISSUE TITLE
SF300 not generate params set . 

### ISSUE THREAD

**Issue by suzhaojun** [ldbc/ldbc_snb_datagen_hadoop#22]
ldbc.snb.datagen.parametergenerator.parameters:true

I use hadoop to generate data sets.
When set ldbc.snb.datagen.generator.scaleFactor:snb.interactive.1,  the data sets have substitution_parameters folder and updateStream_0_0_person.csv updateStream_0_0_forum.csv file.  

But when I ldbc.snb.datagen.generator.scaleFactor:snb.interactive.300, the substitution_parameters folder and update file have not.

I need generate params set.

**Comment by szarnyasg** [comment]
If you get the correct output for a small scale factor but files are missing for the large one, chances are that the generation process failed somewhere. A typical problem is that Hadoop runs out of memory or disk, see https://github.com/ldbc/ldbc_snb_datagen_hadoop/wiki/Troubleshooting for common issues.

My recommendation is to use pre-generated data sets which are available at https://github.com/ldbc/data-sets-surf-repository.

**Comment by suzhaojun** [comment]
> https://github.com/ldbc/ldbc_snb_datagen_hadoop/wiki/Troubleshooting

but excute, not throw exception

**Comment by szarnyasg** [comment]
@suzhaojun The linked site details workarounds for various possible exceptions. If your runs finish but do not result in files, that is highly unusual and will be difficult to troubleshoot. My recommendation would be to use the pre-generated data sets if possible.

**Comment by suzhaojun** [comment]
> @suzhaojun The linked site details workarounds for various possible exceptions. If your runs finish but do not result in files, that is highly unusual and will be difficult to troubleshoot. My recommendation would be to use the pre-generated data sets if possible.

The pre-generated data sets is downloaded very slowly. I want to download SF300.  How to download quickly. Do you have some suggestions or some download ways.

**Comment by szarnyasg** [comment]
1) Some sites allow you to buy VPSs with dedicated bandwidth between EU-China.

2) You can also use a Docker image which may succeed with the generation:
https://github.com/ldbc/ldbc_snb_datagen_hadoop#docker-image

3) Which data sets *exactly* do you need? Paste your `params.ini` file here please.

**Comment by suzhaojun** [comment]
> 1. Some sites allow you to buy VPSs with dedicated bandwidth between EU-China.
> 2. You can also use a Docker image which may succeed with the generation:
>    https://github.com/ldbc/ldbc_snb_datagen_hadoop#docker-image
> 3. Which data sets _exactly_ do you need? Paste your `params.ini` file here please.

Yes, I need the SF300 data sets.
The params.ini  is

ldbc.snb.datagen.generator.scaleFactor:snb.interactive.300
ldbc.snb.datagen.parametergenerator.parameters:true
ldbc.snb.datagen.generator.numThreads:10
ldbc.snb.datagen.serializer.dynamicActivitySerializer:ldbc.snb.datagen.serializer.snb.csv.dynamicserializer.activity.CsvCompositeDynamicActivitySerializer
ldbc.snb.datagen.serializer.dynamicPersonSerializer:ldbc.snb.datagen.serializer.snb.csv.dynamicserializer.person.CsvCompositeDynamicPersonSerializer
ldbc.snb.datagen.serializer.staticSerializer:ldbc.snb.datagen.serializer.snb.csv.staticserializer.CsvCompositeStaticSerializer
ldbc.snb.datagen.util.formatter.StringDateFormatter.dateTimeFormat:yyyy-MM-dd HH:mm:ss
ldbc.snb.datagen.serializer.outputDir:./outputData_test_SF_300/

**Comment by szarnyasg** [comment]
Okay, let me see what I can do. I'll report back in ~4 hours.

**Comment by szarnyasg** [comment]
By the way, is the _initial data set_ (files like `person_0_0.csv`, `comment_0_0.csv`) generated correctly?

**Comment by szarnyasg** [comment]
Hello @suzhaojun, I generated the data set that your config file specifies. It is available in ~7.5 GB chunks and can be downloaded using the following scripts:

```bash
## to download, run:
for N in $(seq 0 1 11); do
    CHUNK=$(printf "%03d" "$N")
    echo "Downloading ${CHUNK}"
    wget -O outputData_test_SF_300.tar.zst.${CHUNK} https://surfdrive.surf.nl/files/index.php/s/MIStKINNdp1lDb4/download?path=%2F\&files=outputData_test_SF_300.tar.zst.${CHUNK}
done
```

```
## to concatenate and decompress, run:
cat *.tar.zst.* | tar -xv --use-compress-program=unzstd
```

HTH

**Comment by szarnyasg** [comment]
@suzhaojun does the provided script/data set work for you? Does it achieve higher download speeds?

**Comment by suzhaojun** [comment]
> @suzhaojun does the provided script/data set work for you? Does it achieve higher download speeds?

Yes, I get it. Thanks very much for your help.

**Comment by szarnyasg** [comment]
I'm glad it help. Can I delete the data set or are you planning to download it in the near future from this URL?
