### ISSUE TITLE
Transfer failed for https://repo.maven.org/maven2/junit/junit/4.12/junit-4.12.jar

### ISSUE THREAD

**Issue by qiaobaaa** [ldbc/ldbc_snb_datagen_hadoop#29]
hi, the following error occurs when running run.sh：
Downloading from simulation: http://www.simulation.tudelft.nl/maven/org/apache/mahout/mahout-collections/1.0/mahout-collections-1.0.jar
Downloading from simulation: http://www.simulation.tudelft.nl/maven/com/github/rwl/optimization/1.3/optimization-1.3.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13:52 min
[INFO] Finished at: 2024-01-16T19:25:30+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ldbc_snb_datagen: Could not resolve dependencies for project ldbc.snb.datagen:ldbc_snb_datagen:jar:1.0.0: The following artifacts could not be resolved: junit:junit:jar:4.12, org.hamcrest:hamcrest-core:jar:1.3, xerces:xercesImpl:jar:2.9.1, xml-apis:xml-apis:jar:1.3.04, xalan:xalan:jar:2.7.1, xalan:serializer:jar:2.7.1, org.jdom:jdom:jar:1.1.3, org.apache.hadoop:hadoop-client:jar:3.2.1, org.apache.hadoop:hadoop-common:jar:3.2.1, com.google.guava:guava:jar:27.0-jre, com.google.guava:failureaccess:jar:1.0, com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava, org.checkerframework:checker-qual:jar:2.5.2, com.google.errorprone:error_prone_annotations:jar:2.2.0, com.google.j2objc:j2objc-annotations:jar:1.1, org.codehaus.mojo:animal-sniffer-annotations:jar:1.17, commons-cli:commons-cli:jar:1.2, org.apache.httpcomponents:httpclient:jar:4.5.6, org.apache.httpcomponents:httpcore:jar:4.4.10, commons-codec:commons-codec:jar:1.11, commons-io:commons-io:jar:2.5, commons-net:commons-net:jar:3.6, commons-collections:commons-collections:jar:3.2.2, org.eclipse.jetty:jetty-servlet:jar:9.3.24.v20180605, org.eclipse.jetty:jetty-security:jar:9.3.24.v20180605, org.eclipse.jetty:jetty-webapp:jar:9.3.24.v20180605, org.eclipse.jetty:jetty-xml:jar:9.3.24.v20180605, javax.servlet.jsp:jsp-api:jar:2.1, com.sun.jersey:jersey-servlet:jar:1.19, commons-logging:commons-logging:jar:1.1.3, log4j:log4j:jar:1.2.17, commons-beanutils:commons-beanutils:jar:1.9.3, org.apache.commons:commons-configuration2:jar:2.1.1, org.apache.commons:commons-lang3:jar:3.7, org.apache.commons:commons-text:jar:1.4, org.slf4j:slf4j-api:jar:1.7.25, org.apache.avro:avro:jar:1.7.7, org.codehaus.jackson:jackson-core-asl:jar:1.9.13, org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13, com.thoughtworks.paranamer:paranamer:jar:2.3, org.xerial.snappy:snappy-java:jar:1.0.5, com.google.re2j:re2j:jar:1.1, com.google.protobuf:protobuf-java:jar:2.5.0, org.apache.hadoop:hadoop-auth:jar:3.2.1, com.nimbusds:nimbus-jose-jwt:jar:4.41.1, com.github.stephenc.jcip:jcip-annotations:jar:1.0-1, net.minidev:json-smart:jar:2.3, net.minidev:accessors-smart:jar:1.2, org.apache.curator:curator-framework:jar:2.13.0, org.apache.curator:curator-client:jar:2.13.0, org.apache.curator:curator-recipes:jar:2.13.0, com.google.code.findbugs:jsr305:jar:3.0.0, org.apache.htrace:htrace-core4:jar:4.1.0-incubating, org.apache.commons:commons-compress:jar:1.18, org.apache.kerby:kerb-simplekdc:jar:1.0.1, org.apache.kerby:kerb-client:jar:1.0.1, org.apache.kerby:kerby-config:jar:1.0.1, org.apache.kerby:kerb-core:jar:1.0.1, org.apache.kerby:kerby-pkix:jar:1.0.1, org.apache.kerby:kerby-asn1:jar:1.0.1, org.apache.kerby:kerby-util:jar:1.0.1, org.apache.kerby:kerb-common:jar:1.0.1, org.apache.kerby:kerb-crypto:jar:1.0.1, org.apache.kerby:kerb-util:jar:1.0.1, org.apache.kerby:token-provider:jar:1.0.1, org.apache.kerby:kerb-admin:jar:1.0.1, org.apache.kerby:kerb-server:jar:1.0.1, org.apache.kerby:kerb-identity:jar:1.0.1, org.apache.kerby:kerby-xdr:jar:1.0.1, com.fasterxml.jackson.core:jackson-databind:jar:2.9.8, com.fasterxml.jackson.core:jackson-core:jar:2.9.8, org.codehaus.woodstox:stax2-api:jar:3.1.4, com.fasterxml.woodstox:woodstox-core:jar:5.0.3, dnsjava:dnsjava:jar:2.1.7, org.apache.hadoop:hadoop-hdfs-client:jar:3.2.1, com.squareup.okhttp:okhttp:jar:2.7.5, com.squareup.okio:okio:jar:1.6.0, com.fasterxml.jackson.core:jackson-annotations:jar:2.9.8, org.apache.hadoop:hadoop-yarn-api:jar:3.2.1, javax.xml.bind:jaxb-api:jar:2.2.11, org.apache.hadoop:hadoop-yarn-client:jar:3.2.1, org.apache.hadoop:hadoop-mapreduce-client-core:jar:3.2.1, org.apache.hadoop:hadoop-yarn-common:jar:3.2.1, javax.servlet:javax.servlet-api:jar:3.1.0, org.eclipse.jetty:jetty-util:jar:9.3.24.v20180605, com.sun.jersey:jersey-core:jar:1.19, javax.ws.rs:jsr311-api:jar:1.1.1, com.sun.jersey:jersey-client:jar:1.19, com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.9.8, com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.9.8, com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.9.8, org.apache.hadoop:hadoop-mapreduce-client-jobclient:jar:3.2.1, org.apache.hadoop:hadoop-mapreduce-client-common:jar:3.2.1, org.apache.hadoop:hadoop-annotations:jar:3.2.1, ca.umontreal.iro:ssj:jar:2.5, jfree:jfreechart:jar:1.0.13, org.apache.mahout:mahout-collections:jar:1.0, jfree:jcommon:jar:1.0.16, colt:colt:jar:1.2.0, concurrent:concurrent:jar:1.3.4, com.github.rwl:optimization:jar:1.3, com.google.code.gson:gson:jar:2.2.4, org.codehaus.groovy:groovy:jar:2.1.6, antlr:antlr:jar:2.7.7, org.ow2.asm:asm-tree:jar:4.0, org.ow2.asm:asm-commons:jar:4.0, org.ow2.asm:asm:jar:4.0, org.ow2.asm:asm-util:jar:4.0, org.ow2.asm:asm-analysis:jar:4.0, org.codehaus.groovy:groovy-templates:jar:2.1.6, org.codehaus.groovy:groovy-xml:jar:2.1.6, org.codehaus.groovy:groovy-jsr223:jar:2.1.6, org.apache.commons:commons-math3:jar:3.4.1, org.roaringbitmap:RoaringBitmap:jar:0.6.18: Could not transfer artifact junit:junit:jar:4.12 from/to central (https://repo.maven.org/maven2): Transfer failed for https://repo.maven.org/maven2/junit/junit/4.12/junit-4.12.jar: Unknown host repo.maven.org -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
JAR does not exist or is not a normal file: /home/smc/software/ldbc_snb_datagen_hadoop/target/ldbc_snb_datagen-1.0.0-jar-with-dependencies.jar
I opened https://repo.maven.org/maven2 in the browser, but it also cannot be opened. How can I solve this problem?  look forward to your reply.

**Comment by szarnyasg** [comment]
@qiaobaaa the Maven process finished for me, it only threw a few warnings about checksums
```
[WARNING] Could not validate integrity of download from https://simulation.tudelft.nl/maven/math/math/1.0.0/math-1.0.0.pom
org.eclipse.aether.transfer.ChecksumFailureException: Checksum validation failed, no checksums available
```

You may try to cleanup your local Maven cache. Be careful, this deletes the whole cache.

```bash
rm -rf ~/.m2/repository
```

You may also want to review your network settings.

Alternatively, you can download pre-generated data sets (conforming to all sorts of Datagen configurations) from the following address:
https://ldbcouncil.org/data-sets-surf-repository/snb-interactive-v1-datagen-v100

**Comment by qiaobaaa** [comment]
> @qiaobaaa the Maven process finished for me, it only threw a few warnings about checksums
> 
> ```
> [WARNING] Could not validate integrity of download from https://simulation.tudelft.nl/maven/math/math/1.0.0/math-1.0.0.pom
> org.eclipse.aether.transfer.ChecksumFailureException: Checksum validation failed, no checksums available
> ```
> 
> You may try to cleanup your local Maven cache. Be careful, this deletes the whole cache.
> 
> ```shell
> rm -rf ~/.m2/repository
> ```
> 
> You may also want to review your network settings.
> 
> Alternatively, you can download pre-generated data sets (conforming to all sorts of Datagen configurations) from the following address: https://ldbcouncil.org/data-sets-surf-repository/snb-interactive-v1-datagen-v100

Thank you so much
