### ISSUE TITLE
Ask something about "Internal Parameters"

### ISSUE THREAD

**Issue by else5789** [ldbc/ldbc_snb_datagen_hadoop#3]
Hi, I'm sorry for disturbing you for something.I tried some times for the guidance in https://github.com/ldbc/ldbc_snb_datagen_hadoop/wiki/Spark，but it didn't work when I set the `generator.dateFormatter`，so can you give something more clear about the parameters? Thank you very much.

**Comment by szarnyasg** [comment]
Hi @else5789, if you're using the Hadoop-based Datagen (which is the one to use with SNB Interactive), then use this for passing a custom data formatter:
https://github.com/ldbc/ldbc_snb_datagen_hadoop/blob/main/params-csv-basic.ini#L8

The page at https://github.com/ldbc/ldbc_snb_datagen_hadoop/wiki/Spark is a mixup of the two Datagen, I'll delete it.
