### ISSUE TITLE
How can I get the raw data including creationdata, deletiondate and explicitlydeleted ?

### ISSUE THREAD

**Issue by prncoprs** [ldbc/ldbc_snb_datagen_hadoop#4]
I find that we can get the raw interactive snb data in the [ldbc_snb_datagen_spark](https://github.com/ldbc/ldbc_snb_datagen_spark) repo. In the raw interactive snb data, there are columns like creationdata, deletiondate and explicitlydeleted. So how can I get the raw data using `ldb_snb_datagen_hadoop` ?

**Comment by szarnyasg** [comment]
Hi @prncoprs,
running deletions is currently not a part of the SNB Interactive workload. We plan to add support for this later (https://github.com/ldbc/ldbc_snb_interactive/issues/173). Then, we'll adjust the Spark-based generator to produce a format that can be consumed by the SNB Interactive driver.
Gabor
