### ISSUE TITLE
Why is no hascreator generated

### ISSUE THREAD

**Issue by shikeno** [ldbc/ldbc_snb_datagen_hadoop#6]
I use main branch, but person_hasCreator_message  not generated

this my generated all dynamic files
![image](https://user-images.githubusercontent.com/44427541/141672470-07648e5a-fe17-418b-85e7-066912cf0e01.png)

**Comment by szarnyasg** [comment]
Hi @shikeno - It seems your setup uses the `CsvMergeForeign` serializer. If you'd like to have a separate CSV file for all edges (e.g. `hasCreator`, `replyOf`), use the `CsvBasic` or the `CsvComposite` serializer.
The differences are explained in the spec: https://ldbcouncil.org/ldbc_snb_docs/ldbc-snb-specification.pdf#page=138

**Comment by shikeno** [comment]
> Hi @shikeno - It seems your setup uses the `CsvMergeForeign` serializer. If you'd like to have a separate CSV file for all edges (e.g. `hasCreator`, `replyOf`), use the `CsvBasic` or the `CsvComposite` serializer. The differences are explained in the spec: https://ldbcouncil.org/ldbc_snb_docs/ldbc-snb-specification.pdf#page=138

thank you for your reply，I found this difference
